spring.application.name=sentinel-api
server.port=8443

debug=false

# Define the bundle
spring.ssl.bundle.jks.sentinel-bundle.key-store.location=classpath:keystore.p12
spring.ssl.bundle.jks.sentinel-bundle.key-store.password=${SERVER_PASS}
spring.ssl.bundle.jks.sentinel-bundle.key-store.type=PKCS12
spring.ssl.bundle.jks.sentinel-bundle.key-alias=sentinel

# Point the server to use that bundle
server.ssl.bundle=sentinel-bundle

# Firmware path
sentinel.firmware.bin-dir=${BIN_PATH:../firmware_binaries/}