spring.application.name=sentinel-api

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password={SERVER_PASS}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=sentinel

sentinel.firmware.bin-dir=${BIN_PATH : .../firmware_binaries/}