spring.application.name=sentinel-api
server.port=8443

debug=false

# PORTABLE SYSTEM PATH: Looks at the root folder of your project repo
spring.ssl.bundle.jks.sentinel-bundle.key-store.location=file:./keystore.p12
spring.ssl.bundle.jks.sentinel-bundle.key-store.password=${SERVER_PASS}
spring.ssl.bundle.jks.sentinel-bundle.key-store.type=PKCS12
spring.ssl.bundle.jks.sentinel-bundle.key-alias=sentinel
spring.ssl.bundle.jks.sentinel-bundle.key.password=${SERVER_PASS}

server.ssl.bundle=sentinel-bundle


sentinel.firmware.bin-dir=${BIN_PATH:../firmware_binaries/}
